#!/bin/bash
#
# bash completion file for debtool


# ensure debtool is on the PATH
_have debtool && {

_lsdebs(){
    # include directories (except hidden ones)
    compgen -d -X '?(*/).*' -- "$cur"

    # include files ending with .deb or .DEB
    compgen -f -X '!*.@(deb|DEB)' -- "$cur"
}

_debtool(){
    local cur prev

    COMPREPLY=()
    cur=${COMP_WORDS[COMP_CWORD]}
    prev=${COMP_WORDS[COMP_CWORD-1]}

    case $prev in
        -b|-br|--build|--fast|-rb|-z)

            # configure pathname completion
            compopt -o filenames &>/dev/null

            # include directories (except hidden ones)
            COMPREPLY=( $( compgen -d -X '?(*/).*' -- "$cur" ) )

            return 0
            ;;

        -c|--combo|-d|--download|-s|--show)

            # include packages in apt-cache
            COMPREPLY=( $( _xfunc dpkg apt-cache pkgnames "$cur" 2>/dev/null ) )

            return 0
            ;;

        -r|--reinst)

            # configure pathname completion
            compopt -o filenames &>/dev/null

            # include directories and debian archives
            COMPREPLY=( $( _lsdebs ) )

            return 0
            ;;

        -u|--unpack)

            # configure pathname completion
            compopt -o filenames &>/dev/null

            # include directories, debian archives, and installed packages
            COMPREPLY=( $( _lsdebs )
                        $( _xfunc dpkg _comp_dpkg_installed_packages "$cur" 2>/dev/null ) )

            return 0
            ;;
    esac

    if [[ $cur = -* ]]; then

        # add completion for all of debtool's command line options
        COMPREPLY=( $( compgen -W '-a --auto -b --build -c --combo -d --download
                                   -f --fast -h --help -q --quiet -r --reinst -s
                                   --show --show-format -u --unpack -z' -- "$cur" ) )
    fi

}

complete -F _debtool debtool

}
